hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Password Generator
description: Create your own passwords that no one will be able to guess!
original_url: https://codeclubprojects.org/en-GB/python/password-generator
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: 'Introduction: '
- title: How secure is your password?
- title: 'Challenge: Creating a better password'
- title: Random characters
- title: 'Challenge: Using numbers and punctuation'
- title: A random password
- title: 'Challenge: A longer password'
- title: Choosing a password length
- title: Lots of passwords
- title: 'Challenge: Choosing the number of passwords'
