hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Password Generator
description: Create your own passwords that no one will be able to guess!
original_url: https://codeclubprojects.org/en-GB/python/password-generator
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: 'Introduction: '
- title: How secure is your password?
- title: 'Challenge: Creating a better password'
- title: Random characters
- title: 'Challenge: Using numbers and punctuation'
- title: A random password
- title: 'Challenge: A longer password'
- title: Choosing a password length
- title: Lots of passwords
- title: 'Challenge: Choosing the number of passwords'