---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Password Generator
description: Create your own passwords that no one will be able to guess!
original_url: https://codeclubprojects.org/en-GB/python/password-generator
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: 'Challenge: Creating a better password'
- title: 'Challenge: Using numbers and punctuation'
- title: 'Challenge: A longer password'
- title: 'Challenge: Choosing the number of passwords'

