---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Generador de contraseñas
description: '¡Crea tus propias contraseñas que nadie podrá adivinar!'
original_url: https://codeclubprojects.org/en-GB/python/password-generator
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introducción'
  - 
    title: '¿Como es de segura tu contraseña?'
  - 
    title: 'Desafío: crear una contraseña mejor'
  - 
    title: Caracteres aleatorios
    completion:
      - engaged
  - 
    title: 'Desafío: uso de números y signos de puntuación'
  - 
    title: Una contraseña aleatoria
  - 
    title: 'Desafío: una contraseña más larga'
  - 
    title: Escogiendo una longitud para la contraseña
  - 
    title: Muchas contraseñas
    completion:
      - internal
  - 
    title: 'Reto: elegir el número de contraseñas'
