---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Generator haseł
description: Stwórz własne hasła, których nikt nie będzie mógł odgadnąć!
original_url: https://codeclubprojects.org/en-GB/python/password-generator
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Wprowadzenie
- title: Jak bezpieczne jest Twoje hasło?
- title: 'Wyzwanie: tworzenie lepszego hasła'
- title: Losowe znaki
  completion:
  - engaged
- title: 'Wyzwanie: używanie liczb i znaków specjalnych'
- title: Losowe hasło
- title: 'Wyzwanie: dłuższe hasło'
- title: Wybór długości hasła
- title: Mnóstwo haseł
  completion:
  - internal
- title: 'Wyzwanie: wybór liczby haseł'
