---
hero_image: images/banner.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Generatore di password
description: Crea password personali che nessuno sarà in grado di indovinare!
original_url: https://codeclubprojects.org/en-GB/python/password-generator
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: What you will make
  - 
    title: Quanto è sicura la tua password?
    completion:
      - engaged
  - 
    title: Random characters
    completion:
      - internal
  - 
    title: Using numbers and punctuation
  - 
    title: A random password
  - 
    title: Choosing a password length
  - 
    title: Lots of passwords
  - 
    title: Choosing the number of passwords
    completion:
      - external
  - 
    title: Create a better password
    challenge: true
  - 
    title: What can you do now?
